version: "3.1"

services:

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb:/data/db

  archiveui:
    image: luids/archiveui:latest
    depends_on:
      - mongodb
    ports:
      - 8000:80
      - 8443:443
    environment:
      - ARCHIVE_HOST=mongodb
    volumes:
      - archiveui_storage:/var/www/storage
      - archiveui_ssl:/etc/apache2/ssl

  luarchive:
    image: luids/luarchive
    volumes:
      - ./etc/luids:/etc/luids
    links:
      - mongodb
    
  xlistd:
    image: luids/xlistd
    volumes:
      - ./etc/luids:/etc/luids
      - xlist:/var/lib/luids/xlist
      - ./data:/var/lib/luids/xlist/local

  xlget:
    image: luids/xlget
    volumes:
      - ./etc/luids:/etc/luids
      - xlist:/var/lib/luids/xlist

  eventproc:
    image: luids/eventproc
    volumes:
      - ./etc/luids:/etc/luids
    links:
      - luarchive

  ludns:
    image: luids/ludns
    volumes:
      - ./etc/luids:/etc/luids
    ports:
      - '1053:53'
      - '1053:53/udp'
    links:
      - xlistd
      - luarchive
      - eventproc

  mongodb-exporter:
    image: bitnami/mongodb-exporter
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
    links:
      - mongodb
 
  prometheus:
    image: prom/prometheus
    volumes:
      - ./etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    links:
      - xlistd
      - ludns
      - eventproc
      - luarchive
      - mongodb-exporter

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./etc/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    links:
      - prometheus

volumes:

  xlist:

  mongodb:

  prometheus:

  archiveui_storage:

  archiveui_ssl:

