@startuml

cloud "Blacklists" {
 [HTTP Server] -left- HTTP
}

cloud "DNS Resolvers" {
 [DNS Resolver] -left- ExtDNS
}

node "Docker" {
  node "docker-volumes" {
    database "mongodb"
    database "xlistdb"
    database "archiveui_storage"
    database "archiveui_ssl"
  }
 
  node "mongo-container" {
    [mongo] -left- TCP_27017 
  }
  [mongo] --> mongodb
  
  node "xlget-container" {
    [xlget] --> [xlistdb]
  }
  [xlget] --> HTTP

  node "xlistd-container" {
    [xlistd] -left- GRPC_X
  }
  [xlistd] --> [xlistdb]
 
  node "luarchive-container" {
    [luarchive] - GRPC_A
  } 
  [luarchive] --> TCP_27017
  
  node "eventproc-container" {
    [eventproc] - GRPC_E
  }
  [eventproc] --> GRPC_A

  node "ludns-container" {
    [ludns] -left- IntDNS
  }

  [ludns] --> GRPC_X
  [ludns] --> ExtDNS
  [ludns] --> GRPC_E
  [ludns] --> GRPC_A

  node "archiveui-container" {
    [archiveui] - TCP_80
    [archiveui] - TCP_443
  }
  [archiveui] --> TCP_27017
  [archiveui] --> archiveui_storage
  [archiveui] --> archiveui_ssl

  [docker-proxy] --> IntDNS
  [docker-proxy] --> TCP_80
  [docker-proxy] --> TCP_443
  [docker-proxy] - DNS
  [docker-proxy] - TCP_8000
  [docker-proxy] - TCP_8443

}

node "Client" {
  [DNS Client] --> DNS
  [HTTP Client] --> TCP_8000
  [HTTP Client] --> TCP_8443
}

@enduml
