[eventproc]
datadir   = "/var/lib/luids/event"

[eventproc.db]
dirs    = [ "/etc/luids/event/events.d" ]

[eventproc.stack]
files   = [ "/etc/luids/event/stacks.json" ]

[ids.api]
files     = [ "/etc/luids/apiservices.json" ]

[server]
listenuri = "tcp://0.0.0.0:5851"

[health]
listenuri  = "tcp://0.0.0.0:8081"
metrics    = true
