version: "3.1"

services:
    
  xlistd:
    image: luids/xlistd
    volumes:
      - ./etc/luids:/etc/luids
      - ./data/my-blacklist.xlist:/var/lib/luids/xlist/my-blacklist.xlist
      - ./data/my-whitelist.xlist:/var/lib/luids/xlist/my-whitelist.xlist

  ludns:
    image: luids/ludns
    volumes:
      - ./etc/luids:/etc/luids
    ports:
      - '1053:53'
      - '1053:53/udp'
    links:
      - xlistd
      
