version: "3.1"

services:
    
  xlistd:
    image: luids/xlistd
    volumes:
      - ./etc/luids:/etc/luids
      - ./data:/var/lib/luids/xlist/local

  ludns:
    image: luids/ludns
    volumes:
      - ./etc/luids:/etc/luids
    ports:
      - '1053:53'
      - '1053:53/udp'
    links:
      - xlistd
      
